In [4]:
import pandas as pd

In [5]:
df1=pd.read_csv('df_merged.csv')

In [6]:
high_valued_transactions=df1[df1['amount'] > 1000]

In [ ]:
high_valued_transactions

,customer_id,name,email,phone,address,registration_date,loyalty_status,country_code,transaction_id,amount,transaction_date,product_category,payment_method,store_location
0,1,Michelle Kidd,vayala@example.net,+971 619-723-4258,"USNS Santiago, FPO AE 80872",25-01-2025,Gold,AE,8,2652.570000,19-04-2025 14:46,Home,Credit Card,New York
1,4,Kimberly Price,jessicaknight@example.com,+1 423-222-9779,"1631 Alexis Meadows, Lake Amanda, CA 75179",08-12-2024,Gold,CA,427,1787.090000,28-04-2025 04:34,Beauty,PayPal,Chicago
2,5,Matthew Phillips,qwilliams@example.com,+1 220-763-3522,"2274 Williams Heights Suite 895, Andersonhaven...",03-02-2024,Gold,OR,452,1983.520000,03-02-2025 14:59,Sports,PayPal,Online
3,7,Louis Miller,patriciaelliott@example.org,+1 198-862-7105,"02590 Marshall Well, Sheppardland, CT 88067",30-09-2024,Gold,CT,470,3241.660000,15-05-2025 15:17,Electronics,PayPal,Los Angeles
6,10,Rachel White,whitemichael@example.org,+1 410-729-9740,"6182 Brown Mountain, South Gary, IL 29016",25-02-2024,Bronze,IL,173,3456.050000,15-04-2025 19:26,Home,Debit Card,Online
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
991,991,Erica Fleming,erica85@example.net,+1 626-453-6078,"55648 Gilbert Square, Port Jessica, OR 63566",21-01-2025,Silver,OR,808,2781.520000,14-05-2025 07:30,Clothing,Credit Card,Los Angeles
992,992,Thomas Stevens,vargasmatthew@example.org,+1 385-454-4879,"8783 Joseph Stravenue Suite 016, Port Gabriell...",25-06-2024,Silver,MT,352,3691.140000,12-02-2025 08:40,Sports,Debit Card,New York
993,995,Deanna Johnson,ycook@example.org,+1 576-320-4824,"601 Contreras Forges, Michaelfurt, KY 30733",01-11-2023,Silver,KY,62,4299.690000,04-01-2025 19:54,Electronics,Debit Card,New York
994,995,Deanna Johnson,ycook@example.org,+1 576-320-4824,"601 Contreras Forges, Michaelfurt, KY 30733",01-11-2023,Silver,KY,129,4653.240000,25-04-2025 23:19,Beauty,Cash,Chicago
999,998,Crystal Brown,pshaffer@example.net,+1 390-747-3088,"095 Janice Forest Suite 570, Boltonmouth, DE 7...",30-08-2024,Bronze,DE,886,2532.550126,16-03-2025 15:42,Beauty,Debit Card,Online